### PR TITLE
Cancel an ongoing file transfer from the popover

### PR DESCRIPTION
**Pull request by torikulhabib**
Once a file transfer is underway the dialog closes and there is no way to cancel the transfer.  This PR provides a way to cancel the transfer by opening the indicator popover and clicking on a button.

https://github.com/elementary/wingpanel-indicator-bluetooth/blob/51bfd0caad2917fd15644d901d87c26e13ab8706/src/Widgets/Device.vala#L192

### CODE REVIEW

**Comment by jeremypw** [comment]
Does this fix an issue? I can still share a file in both directions with an Android phone but I am not sure what the difference is in the UX.

**Comment by torikulhabib** [comment]
@jeremypw when the process sends or receive files dialog that closed to show dialog by clicking on wingpanel doesn't work.

**Comment by jeremypw** [comment]
@torikulhabib Sorry, I do not understand.  Please could you give simple, step by step instructions to reproduce the problem.

**Comment by torikulhabib** [comment]
1. I send files from my cellphone to my computer
2. Our computer will display the progress of receiving files in the popover
3. We want to display the progress dialog received by clicking on the popover that is in progress.
4. but cannot display the ongoing progress dialog.
5. where the progress dialog contains a command to cancel the current progress.

**Comment by torikulhabib** [comment]
this also applies when we send a file then the file progress is still going on but we have closed the dialog window we want to display the closed dialog by clicking on the ongoing bluetooth popover.

**Comment by jeremypw** [comment]
OK, thanks I understand now.

This works, but it would be better and more discoverable if there were a button in the popover to cancel the transfer. Is that possible?

**Comment by torikulhabib** [comment]
I think it will take up too much space.
and also a dialog window is needed for more detailed information regarding the ongoing progress

**Comment by jeremypw** [comment]
I dont think space is really an issue - there is no maximum size for popovers (within reason) and it does not need to be a full-size button .  A clickable icon would suffice.  It needs to be discoverable what clicking on the progress will do. However the design of the popover can be iterated on if required in another PR. My main concern is to get the functionality working.

**Review by jeremypw — APPROVED** [review]

**Pull request merged**
