### PR TITLE
Fix indicator status after restart or resume

### LINKED ISSUE #117: Bluetooth automatically turns on after waking up the laptop from sleep
Even after turning off the Bluetooth in System settings the Bluetooth turns on automatically after waking up the system from sleep. 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91645474-bluetooth-automatically-turns-on-after-waking-up-the-laptop-from-sleep?utm_campaign=plugin&utm_content=tracker%2F59641246&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59641246&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #142: Odin: bluetooth indicator is always ON in the greeter after a reboot
## What Happened

I've disabled bluetooth in my user logged in session which seems to stay that way across reboots. However, the indicator icon in greeter login screen is always enabled and "powered" after a reboot even if I disable it in the greeter login screen.

## Expected Behavior

Indicator should remember the last set status across reboots.

## Steps to Reproduce

1. Restart computer and observe indicator being enabled in greeter login screen.
2. Disable the bluetooth indicator (powered off) via the toggle switch in the popover and restart.
3. Observe that the indicator upon restarting to greeter login screen is once again enabled by itself.

## Platform Information

elementary OS 6 Odin early access - fully updated as of filing this issue.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96101721-odin-bluetooth-indicator-is-always-on-in-the-greeter-after-a-reboot?utm_campaign=plugin&utm_content=tracker%2F59641246&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59641246&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by vjr**
Fixes #142 
Fixes #117 
Fixes https://github.com/elementary/switchboard-plug-bluetooth/issues/159

Note that I do not have any bluetooth devices to test other scenarios like pairing, disconnecting etc.

There is still the issue where the status reverts to enabled after resuming from suspend, so leaving this PR as draft for the time being to see if I can fix it in this PR itself, else will leave it for another PR.

### CODE REVIEW

**Comment by vjr** [comment]
After some searching online and looking at existing issues reported here where sometimes bluetooth turns ON after resume and sometimes it turns OFF after resume, I'm marking this PR ready for review and leave the suspend/resume issue for another PR.

**Comment by vjr** [comment]
OK, last commit apparently fixes the resume from suspend case too.

**Comment by vjr** [comment]
Fixes #117

**Comment by danrabbit** [comment]
I can't confirm that this branch has any impact on the greeter. afaict bluetooth state is being remembered correctly across reboots for both the session and the greeter.

If the intention is to sync the bluetooth enabled state between the session and greeter, that would likely require using elementary settings daemon like we've done for other things

**Comment by vjr** [comment]
Thanks for looking at this!

I tested this on my laptop and desktop, and like your observation, there doesn't seem to be an issue on the laptop, but on the desktop where I have a PCIe addon card (intel ax200 wifi + bluetooth, ASUS brand) this issue occurs across restarts and suspend/resume and this PR fixes the issue there while remaining okay on the laptop.

I don't actually have any bluetooth devices (maybe I can try my phone) to play around with other areas like pairing but this PR code wise doesn't appear to affect any of those areas.

**Comment by vjr** [comment]
I just tried this branch on a new laptop with an Intel AX 201 wifi chipset and the greeter reverts the bluetooth state to ON after a restart here. Will also revisit on my desktop again and update this PR when I get the chance.

**Comment by vjr** [comment]
> I just tried this branch on a new laptop with an Intel AX 201 wifi chipset and the greeter reverts the bluetooth state to ON after a restart here. Will also revisit on my desktop again and update this PR when I get the chance.

Update - this PR works for my laptop and desktop with the intel wifi AX200/201 chipsets and when I had earlier tested on my older laptop (no longer with me) with an intel wifi AC chip (which did not repro the issue) it worked as expected there too.

**Comment by tomaswarynyca** [comment]
@vjr Hello, could you provide a .deb to test the solution?

**Comment by vjr** [comment]
> 
> 
> @vjr Hello, could you provide a .deb to test the solution?

I don't know how to do that, sorry. What version of elementary OS are you running? If you confirm it is the early access Odin version 6.0 then I can perhaps provide the wingpanel plugin library file which you can copy in place, then re-install the original one when done testing. Though I would rather you not mess with your OS installation if you are unable to build from github yourself.

**Comment by vjr** [comment]
Hello @tomaswarynyca  - okay let me try to get you a binary but it may take me a couple of days to find the time to get to this, so please hold on :-)

**Comment by vjr** [comment]
@tomaswarynyca I guess you copy `libbluetooth.so` to `/usr/lib/x86_64-linux-gnu/wingpanel` after making a backup of the existing file, or you could reinstall the original one by running `sudo apt install --reinstall wingpanel-indicator-bluetooth`


[libbluetooth.so.tar.gz](https://github.com/elementary/wingpanel-indicator-bluetooth/files/6544390/libbluetooth.so.tar.gz)

**Comment by tomaswarynyca** [comment]
Great thanks for passing the binary, I have bad news it does not solve the problem :/

**Comment by vjr** [comment]
> > @tomaswarynyca I guess you copy `libbluetooth.so` to `/usr/lib/x86_64-linux-gnu/wingpanel` after making a backup of the existing file, or you could reinstall the original one by running `sudo apt install --reinstall wingpanel-indicator-bluetooth`
> 
> @vjr Great thanks for passing the binary, I have bad news it does not solve the problem :/

Can you mention what steps you followed other than copying the library file? Did you run `killall wingpanel` and let it reload automatically? Or perhaps reboot the system after copying the provided library file?

Let me check my build again - hopefully I gave you the file with my changes and not the default one!

**Comment by tomaswarynyca** [comment]
When copying and entering in the bluetooth, it killed itself. I suspended the machine and the problem continued.
Then I rebooted and it was on, suspended and the same thing happened.

**Comment by vjr** [comment]
okay, i guess it does not work for you. hopefully we are not missing some steps here. ideally would be to build and install from the git branch itself to ensure nothing is missed out - would you be able to try that again? @tomaswarynyca ?

**Comment by tomaswarynyca** [comment]
@vjr Do you know how to solve this problem?

```
Run-time dependency wingpanel-2.0 found: NO (tried pkgconfig and cmake)
meson.build:23:0: ERROR: Dependency "wingpanel-2.0" not found, tried pkgconfig and cmake
```

**Comment by vjr** [comment]
@tomaswarynyca ah i think i also faced this issue before, i think this line https://github.com/vjr/wingpanel-indicator-bluetooth/blob/fix-status-after-restart/meson.build#L25 needs edit to make it "wingpanel-3.0" perhaps... something to do with recent wingpanel versioning changes in master but probably this repo was not updated... can you try changing "wingpanel" to "wingpanel-3.0" (sorry i am away from my Odin machine right now)

**Comment by tomaswarynyca** [comment]
What a jerk I was compiling another branch je
Now it works! Great contribution @vjr

**Review by tomaswarynyca — APPROVED** [review]

**Comment by tomaswarynyca** [comment]
Wait I found a problem, when shutdown/restart and then suspend it keeps the status.
But when startup turns on and off the bluetooth and then suspend it activates itself.

**Comment by vjr** [comment]
> Wait I found a problem, when shutdown/restart and then suspend it keeps the status.
> But when startup turns on and off the bluetooth and then suspend it activates itself.

okay thanks for testing, let me also try these steps on my machines and get back to you... it may take me a couple of days to update here :-)

**Comment by vjr** [comment]
> Wait I found a problem, when shutdown/restart and then suspend it keeps the status.
> But when startup turns on and off the bluetooth and then suspend it activates itself.

I tried some steps which I hope match what you mentioned but it appears to work for me :shrug:

**Comment by tomaswarynyca** [comment]
> I tried some steps which I hope match what you mentioned but it appears to work for me

1- Turn off the bluetooth and turn off the machine.
2- Start the machine and the bluetooth should still be off.
3- Turn bluetooth on and off, now suspend the machine.
4- When resuming and logging in, the bluetooth is still turned off?

**Comment by vjr** [comment]
> > I tried some steps which I hope match what you mentioned but it appears to work for me
> 
> 1- Turn off the bluetooth and turn off the machine.
> 2- Start the machine and the bluetooth should still be off.
> 3- Turn bluetooth on and off, now suspend the machine.
> 4- When resuming and logging in, the bluetooth is still turned off?

Reading your step 4 I presume you are doing steps 1 to 3 in the login screen (greeter) ? I tried either way (in login screen and also after logging into my account) and it is working for me.

I should mention I once noticed the bluetooth indicator in my login account was showing as if it is enabled but clicking on it and the popup tooltip shows it as disabled.

**Comment by tomaswarynyca** [comment]
I did not express myself well in the previous message but it gave me one more thing to try, when I turn off the bluetooth and turn off the machine, turn it on when I start in the login the bluetooth appears on and when I log in it appears off. 

When turning on from the desktop and turning it off, the only fact of locking the machine, makes it turn on only the bluetooth.
Do you have any idea how I can debug the bluetooth status?

**Comment by vjr** [comment]
> I did not express myself well in the previous message but it gave me one more thing to try, when I turn off the bluetooth and turn off the machine, turn it on when I start in the login the bluetooth appears on and when I log in it appears off.
> 
> When turning on from the desktop and turning it off, the only fact of locking the machine, makes it turn on only the bluetooth.
> Do you have any idea how I can debug the bluetooth status?

hmm something is not right, what you are describing seems to be behaviour of the current indicator without this PR fix. are you sure you are running the patched version of the indicator? (i mean, did you run "sudo ninja install" command after the build) ?

also did you run the meson command with the --prefix=/usr option too?

if so, then i guess this branch does not fix the issue for all , just seems to be working on my 2 machines.

**Comment by jeremypw** [comment]
There is another proposed solution here: #131.  I think however both solutions probably need to test whether the indicator is running in a greeter session or a user session and only restore/set the settings in the user session.

**Comment by tomaswarynyca** [comment]
> There is another proposed solution here: #131. I think however both solutions probably need to test whether the indicator is running in a greeter session or a user session and only restore/set the settings in the user session.

I tried this other version and it does not solve the problem it does not keep the status.

**Comment by jeremypw** [comment]
That's what I said - neither PR completely fixes the issue for the reason stated above.

**Comment by tomaswarynyca** [comment]
> That's what I said - neither PR completely fixes the issue for the reason stated above.

I believe that this pr should be merged to partially solve the problem until a better solution is found.

**Comment by jeremypw** [comment]
I have looked into this a bit more and while it is easy enough to find a solution that works for one user logged in at a time, if there are two users logged in with different bluetooth on/off settings then things get weird when you switch between users.  The simplest solution of course would be to discontinue the setting altogether and have the actual hardware be the sole source of truth.  This means that if one user turns off bluetooth then it is off for everyone however.  I'll try a bit more to understand what is going on with simultaneous users.

**Review by jeremypw — APPROVED** [review]
Although this does not always work, it works often so is an improvement and has the benefit of being simple.

**Comment by tomaswarynyca** [comment]
@danrabbit Can you generate a new version to include this fix?

**Pull request merged**
