### PR TITLE
Release 2.1.5

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Comment by cassidyjames** [comment]
Does https://github.com/elementary/wingpanel-indicator-bluetooth/pull/108 have any (potential) user-facing improvements?

**Comment by danrabbit** [comment]
@cassidyjames I'm not certain. Memory usage maybe?

**Comment by cassidyjames** [comment]
Not a huge deal, but pinging @tintou because it'd be nice to include whatever improvements in the release notes at least. Unless it's entirely under-the-hood and doesn't affect users at all.

**Comment by tintou** [comment]
There shouldn't be any feature change with this PR, it should be ready to go :tada:

**Pull request merged**
