### PR TITLE
Device: Subclass Gtk.ListBoxRow

### PR DESCRIPTION
**Pull request by danrabbit**
Subclass Gtk.ListBoxRow instead of Wingpanel.Widgets.Container to solve some padding issues with labels in the row.

This also gives us keyboard activation

### CODE REVIEW

**Comment by jeremypw** [comment]
For me the margin looks wider after installing the PR.  It may be related to the length of the device name/descriptions, which are longer in the illustrated case.

**Comment by jeremypw** [comment]
Looks like an additional margin_start was added to the grid compared to the previous content. Need to check with @danrabbit  whether this was intentional.

**Comment by jeremypw** [comment]
As far as I can see both the description labels in the header switch and the list rows have a start margin of 6 now (and align START).

**Comment by peteruithoven** [comment]
Before > after
Before > after

Comparison before, after, audio, power:
Before, after, audio, power

The padding is now larger indeed, but in my opinion way to large, especially when compared to other indicators. 

The highlighting work though.

**Comment by jeremypw** [comment]
OK, thanks - so the main issue now is the spacing of the menuitems?  Hopefully this hould be fixable.

**Comment by jeremypw** [comment]
The height of the popover is now unchanged:

master-vs-devicerow

      MASTER ---------------------------------------- DEVICEROW

**Comment by jeremypw** [comment]
Closed in error

**Comment by peteruithoven** [comment]
@jeremypw thanks for fixing the vertical margins. I still noticed some difference in the horizontal distance so I've made a tiny PR to this PR.

**Pull request merged**
